library(shiny)
library(shinydashboard)
library(DT)
library(shinyjs)
library(sodium)
library(readr)
library(dplyr)
library(ggplot2)
library(data.table)

allData <- as.data.frame(read_csv("allBaseballData.csv"))